Repository openkruise/charts, pull requests merged in 2022-12, with the labels that each got.

#23 [Issue22] Fix_hardcoded_references_to_namespace
  versions/kruise-rollout/0.2.0/templates/rbac_role.yaml
  versions/kruise-rollout/0.2.0/templates/webhookconfiguration.yaml
  versions/kruise/1.3.0/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.3.0/templates/webhookconfiguration.yaml
Labels: lgtm, approved, size/M

#28 add configmap for kruise game
  versions/kruise-game/0.1.0/templates/controller_manager_config.yaml
  versions/kruise-game/0.1.0/templates/manager.yaml
  versions/kruise-game/0.1.0/templates/rbac_role.yaml
  versions/kruise-game/0.1.0/values.yaml
Labels: lgtm, approved, size/L

#25 Allow to set extra environment variables on manager DaemonSet
  versions/kruise/1.3.0/Chart.yaml
  versions/kruise/1.3.0/README.md
  versions/kruise/1.3.0/templates/manager.yaml
  versions/kruise/1.3.0/values.yaml
Labels: size/S, lgtm, approved

#34 kruise rollout v0.3.0-rc.0
  charts/kruise-rollout
  versions/kruise-rollout/0.3.0-rc.0/.helmignore
  versions/kruise-rollout/0.3.0-rc.0/Chart.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/_helpers.tpl
  versions/kruise-rollout/0.3.0-rc.0/templates/manager.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/rbac_role.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_batchreleases.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_rollouthistories.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/rollouts.kruise.io_rollouts.yaml
  versions/kruise-rollout/0.3.0-rc.0/templates/webhookconfiguration.yaml
  versions/kruise-rollout/0.3.0-rc.0/values.yaml
Labels: size/XXL, lgtm, approved
