Repository openkruise/charts, pull requests merged in 2023-07, with the labels that each got.

#56 kruise-game v0.4.0
  charts/kruise-game
  versions/kruise-game/0.4/.helmignore
  versions/kruise-game/0.4/Chart.yaml
  versions/kruise-game/0.4/README.MD
  versions/kruise-game/0.4/templates/_helpers.tpl
  versions/kruise-game/0.4/templates/alibabacloud.com_poddnats.yaml
  versions/kruise-game/0.4/templates/controller_manager_config.yaml
  versions/kruise-game/0.4/templates/game.kruise.io_gameservers.yaml
  versions/kruise-game/0.4/templates/game.kruise.io_gameserversets.yaml
  versions/kruise-game/0.4/templates/manager.yaml
  versions/kruise-game/0.4/templates/prometheus-monitor.yaml
  versions/kruise-game/0.4/templates/prometheus-service.yaml
  versions/kruise-game/0.4/templates/rbac_role.yaml
  versions/kruise-game/0.4/templates/webhook_service.yaml
  versions/kruise-game/0.4/values.yaml
Labels: size/XXL, lgtm, approved

#57 remove dependency
  versions/kruise-game/0.4/Chart.yaml
  versions/kruise-game/0.4/README.MD
  versions/kruise-game/0.4/values.yaml
Labels: size/S, lgtm, approved

#58 fix chart value
  versions/kruise-game/0.4/values.yaml
Labels: size/XS, lgtm, approved

#59 fix kruise-game 0.4.1
  charts/kruise-game
  versions/kruise-game/0.4.1/.helmignore
  versions/kruise-game/0.4.1/Chart.yaml
  versions/kruise-game/0.4.1/README.MD
  versions/kruise-game/0.4.1/templates/_helpers.tpl
  versions/kruise-game/0.4.1/templates/alibabacloud.com_poddnats.yaml
  versions/kruise-game/0.4.1/templates/controller_manager_config.yaml
  versions/kruise-game/0.4.1/templates/game.kruise.io_gameservers.yaml
  versions/kruise-game/0.4.1/templates/game.kruise.io_gameserversets.yaml
  versions/kruise-game/0.4.1/templates/manager.yaml
  versions/kruise-game/0.4.1/templates/prometheus-monitor.yaml
  versions/kruise-game/0.4.1/templates/prometheus-service.yaml
  versions/kruise-game/0.4.1/templates/rbac_role.yaml
  versions/kruise-game/0.4.1/templates/webhook_service.yaml
  versions/kruise-game/0.4.1/values.yaml
Labels: size/XXL, lgtm, approved

#60 kruise rollout v0.4.0
  charts/kruise-rollout
  versions/kruise-rollout/0.4/.helmignore
  versions/kruise-rollout/0.4/Chart.yaml
  versions/kruise-rollout/0.4/README.md
  versions/kruise-rollout/0.4/templates/_helpers.tpl
  versions/kruise-rollout/0.4/templates/manager.yaml
  versions/kruise-rollout/0.4/templates/rbac_role.yaml
  versions/kruise-rollout/0.4/templates/rollouts.kruise.io_batchreleases.yaml
  versions/kruise-rollout/0.4/templates/rollouts.kruise.io_rollouthistories.yaml
  versions/kruise-rollout/0.4/templates/rollouts.kruise.io_rollouts.yaml
  versions/kruise-rollout/0.4/templates/rollouts.kruise.io_trafficroutings.yaml
  versions/kruise-rollout/0.4/templates/webhookconfiguration.yaml
  versions/kruise-rollout/0.4/values.yaml
Labels: size/XXL, lgtm, approved
