Repository openkruise/charts, pull requests merged in 2023-09, with the labels that each got.

#65 Kruise release 1.5 charts
  charts/kruise
  versions/kruise/1.4/1.5
  versions/kruise/1.5/.helmignore
  versions/kruise/1.5/Chart.yaml
  versions/kruise/1.5/README.md
  versions/kruise/1.5/ci/default-values.yaml
  versions/kruise/1.5/templates/_helpers.tpl
  versions/kruise/1.5/templates/apps.kruise.io_advancedcronjobs.yaml
  versions/kruise/1.5/templates/apps.kruise.io_broadcastjobs.yaml
  versions/kruise/1.5/templates/apps.kruise.io_clonesets.yaml
  versions/kruise/1.5/templates/apps.kruise.io_containerrecreaterequests.yaml
  versions/kruise/1.5/templates/apps.kruise.io_daemonsets.yaml
  versions/kruise/1.5/templates/apps.kruise.io_imagelistpulljobs.yaml
  versions/kruise/1.5/templates/apps.kruise.io_imagepulljobs.yaml
  versions/kruise/1.5/templates/apps.kruise.io_nodeimages.yaml
  versions/kruise/1.5/templates/apps.kruise.io_nodepodprobes.yaml
  versions/kruise/1.5/templates/apps.kruise.io_persistentpodstates.yaml
  versions/kruise/1.5/templates/apps.kruise.io_podprobemarkers.yaml
  versions/kruise/1.5/templates/apps.kruise.io_resourcedistribution.yaml
  versions/kruise/1.5/templates/apps.kruise.io_sidecarsets.yaml
  versions/kruise/1.5/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.5/templates/apps.kruise.io_uniteddeployments.yaml
  versions/kruise/1.5/templates/apps.kruise.io_workloadspreads.yaml
  versions/kruise/1.5/templates/manager.yaml
  versions/kruise/1.5/templates/policy.kruise.io_podunavailablebudgets.yaml
  versions/kruise/1.5/templates/rbac_role.yaml
  versions/kruise/1.5/templates/webhookconfiguration.yaml
  versions/kruise/1.5/values.yaml
Labels: size/XXL, lgtm, approved

#66 Remove unwelcome softlink
  versions/kruise/1.4/1.5
Labels: size/XS, lgtm, approved

#67 modify kruise v1.5.0 cloneset yaml
  versions/kruise/1.5/templates/apps.kruise.io_clonesets.yaml
Labels: lgtm, approved, size/L

#68 reload kruise v1.5.0 chart
  versions/kruise/1.5/values.yaml
Labels: size/XS, lgtm, approved

#69 reload kruise v1.5.0 chart
  versions/kruise/1.5/values.yaml
Labels: size/XS, lgtm, approved
