Repository openkruise/charts, pull requests merged in 2023-02, with the labels that each got.

#37 Fix: fail to install Kruise rollout in customized namespace
  versions/kruise-rollout/0.1.0/templates/manager.yaml
  versions/kruise-rollout/0.3.0-rc/templates/rbac_role.yaml
  versions/kruise-rollout/0.3.0-rc/templates/webhookconfiguration.yaml
Labels: lgtm, approved, size/M

#47 add env GITHUB_TOKEN in publish.yaml
  .github/workflows/publish.yaml
Labels: size/XS, lgtm, approved

#48 Modify publish.yaml
  .github/workflows/publish.yaml
Labels: size/XS, lgtm, approved

#44 kruise state metrics add ServiceMonitor configuration
  versions/kruise-state-metrics/0.1/Chart.yaml
  versions/kruise-state-metrics/0.1/templates/service.yaml
Labels: size/S, lgtm, approved
