Repository openkruise/charts, pull requests merged in 2024-01, with the labels that each got.

#85 krusie 1.5.2
  charts/kruise
  versions/kruise/1.5.2/.helmignore
  versions/kruise/1.5.2/Chart.yaml
  versions/kruise/1.5.2/README.md
  versions/kruise/1.5.2/ci/default-values.yaml
  versions/kruise/1.5.2/templates/_helpers.tpl
  versions/kruise/1.5.2/templates/apps.kruise.io_advancedcronjobs.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_broadcastjobs.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_clonesets.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_containerrecreaterequests.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_daemonsets.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_imagelistpulljobs.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_imagepulljobs.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_nodeimages.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_nodepodprobes.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_persistentpodstates.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_podprobemarkers.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_resourcedistribution.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_sidecarsets.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_uniteddeployments.yaml
  versions/kruise/1.5.2/templates/apps.kruise.io_workloadspreads.yaml
  versions/kruise/1.5.2/templates/manager.yaml
  versions/kruise/1.5.2/templates/policy.kruise.io_podunavailablebudgets.yaml
  versions/kruise/1.5.2/templates/rbac_role.yaml
  versions/kruise/1.5.2/templates/webhookconfiguration.yaml
  versions/kruise/1.5.2/values.yaml
Labels: size/XXL, lgtm, approved

#86 kruise 1.4.1
  versions/kruise/1.4.1/.helmignore
  versions/kruise/1.4.1/Chart.yaml
  versions/kruise/1.4.1/README.md
  versions/kruise/1.4.1/ci/default-values.yaml
  versions/kruise/1.4.1/templates/_helpers.tpl
  versions/kruise/1.4.1/templates/apps.kruise.io_advancedcronjobs.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_broadcastjobs.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_clonesets.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_containerrecreaterequests.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_daemonsets.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_imagepulljobs.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_nodeimages.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_nodepodprobes.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_persistentpodstates.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_podprobemarkers.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_resourcedistribution.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_sidecarsets.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_uniteddeployments.yaml
  versions/kruise/1.4.1/templates/apps.kruise.io_workloadspreads.yaml
  versions/kruise/1.4.1/templates/manager.yaml
  versions/kruise/1.4.1/templates/policy.kruise.io_podunavailablebudgets.yaml
  versions/kruise/1.4.1/templates/rbac_role.yaml
  versions/kruise/1.4.1/templates/webhookconfiguration.yaml
  versions/kruise/1.4.1/values.yaml
Labels: size/XXL, lgtm, approved

#87 add kube-state-metric 0.2 chart
  charts/kruise-state-metrics
  versions/kruise-state-metrics/0.2/.helmignore
  versions/kruise-state-metrics/0.2/Chart.yaml
  versions/kruise-state-metrics/0.2/templates/_helpers.tpl
  versions/kruise-state-metrics/0.2/templates/deployment.yaml
  versions/kruise-state-metrics/0.2/templates/service.yaml
  versions/kruise-state-metrics/0.2/templates/serviceaccount.yaml
  versions/kruise-state-metrics/0.2/values.yaml
Labels: lgtm, approved, size/L

#88 kruise 1.3.1
  charts/kruise
  versions/kruise/1.3.1/.helmignore
  versions/kruise/1.3.1/Chart.yaml
  versions/kruise/1.3.1/README.md
  versions/kruise/1.3.1/ci/default-values.yaml
  versions/kruise/1.3.1/templates/_helpers.tpl
  versions/kruise/1.3.1/templates/apps.kruise.io_advancedcronjobs.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_broadcastjobs.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_clonesets.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_containerrecreaterequests.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_daemonsets.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_imagepulljobs.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_nodeimages.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_nodepodprobes.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_persistentpodstates.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_podprobemarkers.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_resourcedistribution.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_sidecarsets.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_uniteddeployments.yaml
  versions/kruise/1.3.1/templates/apps.kruise.io_workloadspreads.yaml
  versions/kruise/1.3.1/templates/manager.yaml
  versions/kruise/1.3.1/templates/policy.kruise.io_podunavailablebudgets.yaml
  versions/kruise/1.3.1/templates/rbac_role.yaml
  versions/kruise/1.3.1/templates/webhookconfiguration.yaml
  versions/kruise/1.3.1/values.yaml
Labels: size/XXL, lgtm, approved

#89 kruise 1.4.1
  charts/kruise
Labels: size/XS, lgtm, approved
