Repository openkruise/charts, pull requests merged in 2024-08, with the labels that each got.

#108 add external certs
  versions/kruise/1.7.0-alpha.1/README.md
  versions/kruise/1.7.0-alpha.1/templates/apps.kruise.io_statefulsets.yaml
  versions/kruise/1.7.0-alpha.1/templates/rbac_role.yaml
  versions/kruise/1.7.0-alpha.1/templates/webhookconfiguration.yaml
  versions/kruise/1.7.0-alpha.1/values.yaml
Labels: lgtm, approved, size/L

#113 kruise game 0.9.0
  charts/kruise-game
  versions/kruise-game/0.9/.helmignore
  versions/kruise-game/0.9/Chart.yaml
  versions/kruise-game/0.9/README.md
  versions/kruise-game/0.9/templates/_helpers.tpl
  versions/kruise-game/0.9/templates/alibabacloud.com_poddnats.yaml
  versions/kruise-game/0.9/templates/controller_manager_config.yaml
  versions/kruise-game/0.9/templates/game.kruise.io_gameservers.yaml
  versions/kruise-game/0.9/templates/game.kruise.io_gameserversets.yaml
  versions/kruise-game/0.9/templates/manager.yaml
  versions/kruise-game/0.9/templates/prometheus-monitor.yaml
  versions/kruise-game/0.9/templates/rbac_role.yaml
  versions/kruise-game/0.9/templates/scaler-service.yaml
  versions/kruise-game/0.9/templates/webhook_service.yaml
  versions/kruise-game/0.9/values.yaml
Labels: size/XXL, lgtm, approved

#115 modify kruise 1.7.0
  charts/kruise
Labels: lgtm, approved
